Hi!

So this is what I see.

import pandas as pd
from pandasgui import show

df = pd.DataFrame(([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=['a', 'b', 'c'])
show(df)


AND about from pandasgui import show - somethin go wrong:




---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-488ae1300181> in <module>
----> 1 from pandasgui import show

c:\users\ii\appdata\local\programs\python\python37\lib\site-packages\pandasgui\__init__.py in <module>
      9 
     10 # Imports
---> 11 from pandasgui.gui import show
     12 
     13 __all__ = ["show"]

c:\users\ii\appdata\local\programs\python\python37\lib\site-packages\pandasgui\gui.py in <module>
     12 from pandasgui.store import PandasGuiStore, PandasGuiDataFrameStore
     13 from pandasgui.utility import fix_ipython, fix_pyqt, as_dict, delete_datasets, resize_widget
---> 14 from pandasgui.widgets.dataframe_explorer import DataFrameExplorer
     15 from pandasgui.widgets.find_toolbar import FindToolbar
     16 from pandasgui.widgets.json_viewer import JsonViewer

c:\users\ii\appdata\local\programs\python\python37\lib\site-packages\pandasgui\widgets\dataframe_explorer.py in <module>
      7 from pandasgui.utility import nunique
      8 from pandasgui.widgets.dataframe_viewer import DataFrameViewer
----> 9 from pandasgui.widgets.grapher import Grapher
     10 from pandasgui.widgets.reshaper import Reshaper
     11 from pandasgui.widgets.filter_viewer import FilterViewer

c:\users\ii\appdata\local\programs\python\python37\lib\site-packages\pandasgui\widgets\grapher.py in <module>
     15 from pandasgui.store import PandasGuiStore, PandasGuiDataFrameStore, HistoryItem
     16 
---> 17 from pandasgui.widgets.plotly_viewer import PlotlyViewer, plotly_markers
     18 from pandasgui.utility import flatten_df, flatten_iter, kwargs_string, nunique, unique
     19 from pandasgui.widgets.plotly_viewer import PlotlyViewer

c:\users\ii\appdata\local\programs\python\python37\lib\site-packages\pandasgui\widgets\plotly_viewer.py in <module>
     38 # Available symbol names for a given version of Plotly
     39 _extended_symbols = SymbolValidator().values[0::2][1::3]
---> 40 plotly_markers = [symbol for symbol in _extended_symbols if symbol[-3:] != "dot"]
     41 
     42 

c:\users\ii\appdata\local\programs\python\python37\lib\site-packages\pandasgui\widgets\plotly_viewer.py in <listcomp>(.0)
     38 # Available symbol names for a given version of Plotly
     39 _extended_symbols = SymbolValidator().values[0::2][1::3]
---> 40 plotly_markers = [symbol for symbol in _extended_symbols if symbol[-3:] != "dot"]
     41 
     42 

TypeError: 'int' object is not subscriptable



BUT the "pip install" was OK:

Requirement already satisfied: pandasgui in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (0.2.9)
Requirement already satisfied: setuptools in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from pandasgui) (51.1.0)
Requirement already satisfied: PyQt5-sip in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from pandasgui) (12.8.0)
Requirement already satisfied: dacite in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from pandasgui) (1.6.0)
Requirement already satisfied: pynput in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from pandasgui) (1.7.3)
Requirement already satisfied: pandas in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from pandasgui) (1.0.5)
Requirement already satisfied: plotly in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from pandasgui) (4.9.0)
Requirement already satisfied: wordcloud in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from pandasgui) (1.8.1)
Requirement already satisfied: pyarrow in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from pandasgui) (3.0.0)
Requirement already satisfied: appdirs in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from pandasgui) (1.4.4)
Requirement already satisfied: IPython in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from pandasgui) (7.16.1)
Requirement already satisfied: astor in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from pandasgui) (0.8.1)
Requirement already satisfied: PyQt5 in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from pandasgui) (5.15.0)
Requirement already satisfied: PyQtWebEngine in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from pandasgui) (5.15.2)
Requirement already satisfied: colorama in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from IPython->pandasgui) (0.4.3)
Requirement already satisfied: pickleshare in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from IPython->pandasgui) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from IPython->pandasgui) (4.3.3)
Requirement already satisfied: pygments in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from IPython->pandasgui) (2.6.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from IPython->pandasgui) (3.0.5)
Requirement already satisfied: jedi>=0.10 in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from IPython->pandasgui) (0.17.2)
Requirement already satisfied: decorator in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from IPython->pandasgui) (4.4.2)
Requirement already satisfied: backcall in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from IPython->pandasgui) (0.2.0)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from jedi>=0.10->IPython->pandasgui) (0.7.0)
Requirement already satisfied: wcwidth in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->IPython->pandasgui) (0.2.5)
Requirement already satisfied: six in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from traitlets>=4.2->IPython->pandasgui) (1.15.0)
Requirement already satisfied: ipython-genutils in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from traitlets>=4.2->IPython->pandasgui) (0.2.0)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from pandas->pandasgui) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from pandas->pandasgui) (2020.1)
Requirement already satisfied: numpy>=1.13.3 in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from pandas->pandasgui) (1.19.0)
Requirement already satisfied: retrying>=1.3.3 in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from plotly->pandasgui) (1.3.3)
Requirement already satisfied: matplotlib in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from wordcloud->pandasgui) (3.3.0)
Requirement already satisfied: pillow in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from wordcloud->pandasgui) (7.2.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from matplotlib->wordcloud->pandasgui) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from matplotlib->wordcloud->pandasgui) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\ii\appdata\local\programs\python\python37\lib\site-packages (from matplotlib->wordcloud->pandasgui) (2.4.7)
Note: you may need to restart the kernel to use updated packages.
